module.exports={
    devServer:{
        proxy:{
            "/api":{
                target:"https://b2capigateway.yiguo.com",
                changeOrigin:true,
                pathRewrite:{
                    "^/api":"/"
                }
            },
            "/dd":{
                target:"http://10.9.26.162:3000/",
                changeOrigin:true,
                pathRewrite:{
                    "^/dd":"/"
                }
            }
        }
    },
}