module.exports={
    devServer:{
        proxy:{
            "/api":{
                target:"https://b2capigateway.yiguo.com",
                changeOrigin:true,
                pathRewrite:{
                    "^/api":"/"
                }
            }
        }
    }
}